version: 2
jobs:
  build_lambda:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/lambda/package.json" }}
      - run: pwd
      - run: cd packages/lambda && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "packages/lambda/package.json" }}
          paths:
            - packages/lambda/node_modules
      - run:
          name: Integration test
          command: cd packages/lambda && npm run test:integration

  test_lambda:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/lambda/package.json" }}
      - run:
          name: Integration test
          command: cd packages/lambda && npm run test:integration

  test_serverless_plugin:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: cd packages/serverless-plugin && npm install

  test_serverless_example:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: cd packages/serverless-plugin && npm install

workflows:
  version: 2
  lambda:
    jobs:
      - build_lambda
      - test_lambda:
          requires:
            - build_lambda
  serverless_plugin:
    jobs:
      - test_serverless_plugin
  examples:
    jobs:
      - test_serverless_example
