version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: cd packages/lambda && npm install
      - run: cd packages/serverless-plugin && npm install
      - run: cd examples/serverless-framework/aws && npm install
  test:
    steps:
      - checkout
      - run:
          name: AWS Lambda binary integration test
          command: cd packages/lambda && npm run test:integration

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
