version: 2
jobs:
  test_lambda:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: cd packages/lambda && npm install
      - run:
          name: Integration test
          command: cd packages/lambda && npm run test:integration

  test_serverless_plugin:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: cd packages/serverless-plugin && npm install

  test_serverless_example:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: cd packages/serverless-plugin && npm install

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_lambda
      - test_serverless_plugin
      - test_serverless_example
      # - test:
      #     requires:
      #       - build
