version: 2
jobs:
  build_lambda:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/lambda/package.json" }}
      - run: cd packages/lambda && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "packages/lambda/package.json" }}
          paths:
            - packages/lambda/node_modules

  test_lambda:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/lambda/package.json" }}
      - run:
          name: Integration test
          command: cd packages/lambda && npm run test:integration

  test_serverless_plugin:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/serverless-plugin/package.json" }}
      - run: cd packages/serverless-plugin && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "packages/serverless-plugin/package.json" }}
          paths:
            - packages/serverless-plugin/node_modules
  test_serverless_example:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "examples/serverless-framework/aws/package.json" }}
      - run: cd examples/serverless-framework/aws && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "examples/serverless-framework/aws/package.json" }}
          paths:
            - examples/serverless-framework/aws/node_modules      

workflows:
  version: 2
  lambda:
    jobs:
      - build_lambda
      - test_lambda:
          requires:
            - build_lambda
  serverless_plugin:
    jobs:
      - test_serverless_plugin
  examples:
    jobs:
      - test_serverless_example
