service: serverless-chrome-examples

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    DEBUG: "*"
    PAGE_LOAD_TIMEOUT: 30000
    LOGGING: true

plugins:
  - serverless-plugin-chrome
  #- serverless-webpack
  - serverless-apigwy-binary  # For Raw Binary responses only

custom:
  chromeFlags:
    - --window-size=1280x1696 # Letter size
    - --hide-scrollbars

functions:
  version-info:
    description: Headless Chrome Serverless-framework version info example
    memorySize: 1024
    timeout: 30
    handler: src/versionInfo.handler
    events:
      - http:
          path: version-info
          method: get

  request-logger:
    description: Headless Chrome Serverless-framework request logging example
    memorySize: 1024
    timeout: 30
    handler: src/requestLogger.handler
    events:
      - http:
          path: request-logger
          method: get

  screenshot-binary:
    description: Headless Chrome Serverless-framework screenshot example (returns binary)
    memorySize: 1536
    timeout: 30
    handler: src/captureScreenshotBinary.handler
    events:
      - http:
          path: screenshot
          method: get
          contentHandling: CONVERT_TO_BINARY

  screenshot-html:
    description: Headless Chrome Serverless-framework screenshot example (returns html)
    memorySize: 1536
    timeout: 30
    handler: src/captureScreenshotHtml.handler
    events:
      - http:
          path: screenshot-html
          method: get

  pdf-binary:
    description: Headless Chrome Serverless-framework pdf example (returns binary)
    memorySize: 1536
    timeout: 30
    handler: src/printToPdfBinary.handler
    events:
      - http:
          path: pdf
          method: get
          contentHandling: CONVERT_TO_BINARY

  pdf-html:
    description: Headless Chrome Serverless-framework pdf example (returns html)
    memorySize: 1536
    timeout: 30
    handler: src/printToPdfHtml.handler
    events:
      - http:
          path: pdf-html
          method: get
