service: serverless-chrome-examples

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
     -  Effect: "Allow"
        Action:
          - "s3:GetBucketNotification"
          - "s3:PutBucketNotification"
        Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::app.acidvr.com"
  stage: dev
  region: us-east-1
  environment:
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true

plugins:
  localPath: ./node_modules/serverless-chrome
  modules:
    - serverless-webpack
    - serverless-plugin-existing-s3

custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars
      - --enable-accelerated-2d-canvas
      - --allow-hidden-media-playback
      - --enable-usermedia-screen-capturing
      - --disable-setuid-sandbox
      - --enable-webgl
      - --mute-audio
      - --disable-breakpad
      - --ignore-gpu-blacklist
    functions:
      - captureAframe

functions:
  captureAframe:
    description: Capture A-frame scene video
    memorySize: 2048
    timeout: 300
    handler: src/handlers/captureAframe.default
    events:
      - existingS3:
          bucket: app.acidvr.com
          event: s3:ObjectCreated:*
          rules:
            - prefix: liquidlyrics/capture
            - suffix: .html
