service: serverless-chrome-examples

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: false

plugins:
  - serverless-plugin-chrome
  - serverless-webpack

custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars

functions:
  captureAframe:
    description: Headless Chrome Serverless-framework capture video from A-frame scene
    memorySize: 2048
    timeout: 30
    handler: src/handlers/captureAframe.default
    events:
      - http:
          path: captureaframe
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

    # Enable X-Ray tracing on Lambda functions
    # ScreenshotLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
    # PdfLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
